version: "3"
services:
  nodemy-app:
    container_name: nodemy-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - JWT_SECRET=$JWT_SECRET
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - HOST=$HOST
      - PHASE=$PHASE
    volumes:
      - /home/videos:/home/videos
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "443:443"
    links:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: nodemy-db
    image: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - /root/nodemy-db:/home/nodemy-db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge